spring.application.name=scoring-service
server.port=${PORT:8082}

spring.config.import=optional:file:../.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/f1predict_scoring?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

services.f1.url=${F1_SERVICE_URL:http://localhost:8081}
services.prediction.url=${PREDICTION_SERVICE_URL:http://localhost:8083}
services.auth.url=${AUTH_SERVICE_URL:http://localhost:8084}


messaging.provider=${MESSAGING_PROVIDER:rabbitmq}
spring.cloud.gcp.project-id=${GOOGLE_CLOUD_PROJECT:f1-fantasy-510117}
spring.cloud.gcp.sql.enabled=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=${JWT_SECRET}

