spring.application.name=api-gateway

spring.config.import=optional:file:../.env[.properties]

server.port=8080

jwt.secret=${JWT_SECRET}

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://${AUTH_SERVICE_HOST:localhost}:8084
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=f1-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://${F1_SERVICE_HOST:localhost}:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/f1/**

spring.cloud.gateway.server.webflux.routes[2].id=predict-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://${PREDICT_SERVICE_HOST:localhost}:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/predictions/**

spring.cloud.gateway.server.webflux.routes[3].id=scoring-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://${SCORING_SERVICE_HOST:localhost}:8082
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/scoring/**