#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/f1predict
#spring.datasource.username=${MYSQL_USER:laravel}
#spring.datasource.password=${MYSQL_PASSWORD:laravel}

# Usa localhost e a porta 3307 (a porta mapeada no host)
spring.datasource.url=jdbc:mysql://localhost:3307/f1predict?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Hibernate properties
spring.jpa.show-sql=true

# Specify the dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

