spring.application.name=predict-service
server.port=8083

spring.config.import=optional:file:../.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3307/f1predict_predict?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}

services.f1.url=http://localhost:8081