version: "3"
services:
  spring-boot-app:
    container_name: spring-boot-app
    image: zmartins11/springf1-image:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: f1predict
      MYSQL_ROOT_PASSWORD: root

  angular-app:
    image: zmartins11/angularf1-image:latest
    ports:
      - "80:80"

  python-flask-app:
    container_name: python-flask-app
    image: zmartins11/pythonf1-image:latest
    restart: always
    ports:
      - "5000:5000"