name: Deploy Application

on:
  push:
    branches: [off-season]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t zmartins11/springf1-image .
      - name: Push image docker
        run: docker push zmartins11/springf1-image

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop Docker Compose
        run: sudo docker-compose -f /home/ec2-user/code/docker-compose.yml down
      - name: Remove existing Spring Image
        run: sudo docker rmi springf1-image
      - name: Pull image from docker hub
        run: sudo docker pull zmartins11/springf1-image