name: Deploy Angular Application

on:
  push:
    branches: [off-season]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fantasyAngular/fantasyAngular

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --force

      - name: Build Angular app
        run: npm run build --prod

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Angular app
        run: docker build -t zmartins11/angularf1-image .

      - name: Push Docker image for Angular app
        run: docker push zmartins11/angularf1-image


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove existing Angular Image
        run: sudo docker rmi zmartins11/angularf1-image
      - name: Pull image from docker hub
        run: sudo docker pull zmartins11/angularf1-image
      - name: Run docker compose
        run: sudo docker-compose -f /home/ec2-user/code/docker-compose.yml up -d